[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "livebench"
version = "0.0.4"
description = "A living benchmark for large language models."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "aiohttp", "anthropic>=0.3", "antlr4-python3-runtime==4.11", "datasets", "fastapi", "httpx",
    "levenshtein>=0.20.4", "lxml", "markdown2[all]", "nh3", "nltk", "numpy", "openai", "google-genai", "together",
    "packaging", "pandas==2.2.2", "prompt_toolkit>=3.0.0", "protobuf", "pydantic", "psutil", "requests", "rich>=10.0.0",
    "shortuuid", "sympy>=1.12", "tiktoken", "tqdm>=4.62.1", "uvicorn", "wheel",
    "tenacity", "lark", "pyyaml",
    "docker", "gitpython", "toml", "PyGithub", "unidiff", "rich-argparse", "litellm", "swe-rex>=1.4.0", "tabulate", "textual>=1.0.0", "jinja2",
    "typer", "giga @ git+https://git@gitlab.com/ru.ush/lightweight-gigachat.git@module", "langdetect", "immutabledict",
]

[project.optional-dependencies]
flash_attn  = ["flash-attn"]
local-models = [
    "accelerate>=0.21",
    "torch",
    "transformers>=4.31.0",
    "peft",
    "sentencepiece",
    "ray",
    "fastchat",
    "fschat@git+https://github.com/lm-sys/FastChat#egg=c5223e34babd24c3f9b08205e6751ea6e42c9684",
    "langchain",
    "pydantic_settings",
    "dataclasses_json",
    "simple-parsing",
    "platformdirs",
    "ruamel.yam",
]

[project.urls]
"Homepage" = "https://github.com/livebench/LiveBench"
"Bug Tracker" = "https://github.com/livebench/LiveBench/issues"

[tool.setuptools.packages.find]
exclude = ["notebooks"]

[tool.wheel]
exclude = ["notebooks"]
